language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: CN+ISHe8zi9TS7eMbOuYmWrkH99+BluxeihydxTHX4y9pgDyuc+NMASjokjbYPj8tVWIKQmGK1ckIAREWb5RmXhKMT2ba0KM/5WXTUwTHcl2O9EbRp0QPyCgL2Lyg9ExDChSa0f/6E+c5IbY1FCISVyNXq9y0w6tkxm/qXvXo8rZnWt3teZay0hTYIWWRFdXTuJRFSxdRf3LM7aUw4mTkXm9+2AZ07i9k9WeL9sprHIth2rwIZu3ciMtmQBq28zvIAYRmoft1Kf1ptjG3fz3qgeaDEAC/PEivHBRvDHCVAxNcb3+i5ANyPaj7jsWdPFh5QmIE4vQBoQDzyuRJEo4FdScIH8yGoHvNrWDe0grhKHD2JgVLwOLUVIvGmTXuNkxWvI7Bqg6L7PAD/qMQBrj0xHE4ca/Wzd2ka3mAKHufeapYNiIR6vRr7+x4EKKq2R5bDL5Wi/d7t51rkQEQW5kLYRnNVRd+nATkalawE+clA4VCR0U9S5fL/gqptppaOo1AbTxYdf2t4zgnqELMe0eez2Xe6EDjNWhFZvVldVW53En+YpRbXr3ggP6Xw8XdwwTxF3eTBQH8d0edV9AL4HvR+NUp26tkEuHjtOyF0R9LvjUu/58697bK0KwSK2K9E2h2POt7nm5ANxl6tUDI1FXB1/LkN74tCEHuCYw+gn9qYI=
  app: git diff
  on:
    repo: jonathanbeaty/node-shopping-list-integration-tests

deploy: floating-taiga-18425
